name: Deployment pipeline
env:
  SKIP: ${{ contains(github.event.head_commit.message, '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:    
    branches: [main]    
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  deploy_and_tag:
    if: ${{ (github.event_name == 'push') && !(contains(github.event.head_commit.message, '#skip')) }}
    name: Deploy app
    needs: simple_deployment_pipeline
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.version_tag.outputs.new_tag }}
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - id: deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Failure notifications
        if: ${{ needs.deploy_and_tag.result == 'failure' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          DISCORD_EMBEDS: '[{
            "title": "Deployment Failed", 
            "description": "Commit ${{ github.sha }} failed to deploy.",
            "color": 14686985
            }]'
        uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554
      - name: version_tag
        id: version_tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  success_notification:
    needs: [deploy_and_tag]
    runs-on: ubuntu-latest
    steps:
      - name: Success notifications
        if: ${{ needs.deploy_and_tag.result == 'success' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          DISCORD_EMBEDS: '[{
            "title": "Deployment Succeeded", 
            "description": "Version ${{ needs.deploy_and_tag.outputs.new_tag}} deployed successfully.",
            "color": 647195
            }]'
        uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554


