name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.head_commit.message) }}
        if: contains (env.COMMIT_MESSAGES, '#skip')
        run: echo "skipping"